make code blocks dependent on their file and not the active one
SkepticMystic/breadcrumbs pull request #528
Opened 2024-04-10 20:53 UTC by mProjectsCode

2024-04-10 20:56 UTC, SkepticMystic commented
Thank you :) I'll check this out tomorrow

2024-04-11 06:57 UTC, SkepticMystic requested changes

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockMermaid.svelte
> +	let all_paths = [];
Please type this, `BCEdge[][]`

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockMermaid.svelte
> +	$: active_file_path = file_path ? file_path : ($active_file_store ? $active_file_store.path : undefined);
We should fallback to `''` instead of `undefined`, right? Most callers expect start_node to atleast be an empty string

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockMermaid.svelte
> +	$: active_file_path = file_path ? file_path : ($active_file_store ? $active_file_store.path : undefined);
And if we just fallback to `''`, then the `file_path` prop is always fine, we don't even need to check `active_file_store`

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockMermaid.svelte
> +	});
Initialise `distances` as well. Probably easiest to just call `update` onMount

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockMermaid.svelte
> +				const source_path = active_file_path ?? "";
We won't need to fallback here after changing the above

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockMermaid.svelte
> +				active_file_path ?? "",
We won't need to fallback here after changing the above

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockTree.svelte
> +	let all_paths = [];
Add a type

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockTree.svelte
> +	$: active_file_path = file_path ? file_path : ($active_file_store ? $active_file_store.path : undefined);
Same here, we don't need the intermediate variable or fallbacks. `file_path` is always a string, and empty is fine

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockTree.svelte
> +	});
Call `update` instead

2024-04-11 06:57 UTC, SkepticMystic commented on src/components/codeblocks/CodeblockMermaid.svelte
> +	$: active_file_path = file_path ? file_path : ($active_file_store ? $active_file_store.path : undefined);
Either way, `get_all_paths` will just return `[]` in the else case, but ensuring a string makes TS happy

2024-04-11 09:56 UTC, mProjectsCode commented
Fixed all the things, I hope

2024-04-11 10:01 UTC, merged